### ISSUE TITLE
async for is not supported

### ISSUE THREAD

**Issue by derrix060** [best-doctor/flake8-expression-complexity#15]
```python
async def function():
    async for i in range(10):
        print(i)
```
raises AssertionError: should always get node type on python 3.8

**Comment by rogsme** [comment]
Hi! Is there any timeline for this fix? I see a PR is open, but it is waiting for merge. In the meantime, I've installed it by using `git+https` pointing to `derrix060/flake8-expression-complexity` branch

**Comment by derrix060** [comment]
The PR is good to go, just need a re-review from the maintainers...
